export const FETCH_CREDIT_CARD = "FETCH_CREDIT_CARD";


export const UPDATE_CREDIT_CARD_SUCCESS = "UPDATE_CREDIT_CARD_SUCCESS";
export const UPDATE_CREDIT_CARD_FAIL = "UPDATE_CREDIT_CARD_FAIL";
export const UPDATE_CREDIT_CARD_START = "UPDATE_CREDIT_CARD_START";
