export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';

export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';
export const UPDATE_ITEM_START = 'UPDATE_ITEM_START';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';

export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const ADD_ITEM_START = 'ADD_ITEM_START';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';

export const FETCH_ITEMS = 'FETCH_ITEMS';
