export const DONATE_MONEY_START = "DONATE_MONEY_START";
export const DONATE_MONEY_FAIL = "DONATE_MONEY_FAIL";
export const DONATE_MONEY_SUCCESS = "DONATE_MONEY_SUCCESS";
export const SHOW_MONEY_DONATIONS = "SHOW_MONEY_DONATIONS";
